/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author davidf
 */
public class viewConsults extends JDialog {

    /**
     * Creates new form viewSearch
     * @param parent
     * @param modal
     */
    
       imagenPanel fondo = new imagenPanel();
    public viewConsults(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
   this.setContentPane(fondo);
        
        initComponents();
        setWindow();
    }

    public JButton getBtnClean() {
        return btnClean;
    }

    public JButton getBtnExit() {
        return btnExit;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public JButton getBtnSeeDetails() {
        return btnSeeDetails;
    }

    public JTable getJtableWarList() {
        return jtableWarList;
    }

    public JLabel getLblDetailsWar() {
        return lblDetailsWar;
    }

    public JLabel getLblFilterWar() {
        return lblFilterWar;
    }

    public JTextArea getTxtAreaDetailsWar() {
        return txtAreaDetailsWar;
    }

    public JTextField getTxtfFilterWar() {
        return txtfFilterWar;
    }



    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFilterWar = new javax.swing.JLabel();
        txtfFilterWar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableWarList = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDetailsWar = new javax.swing.JTextArea();
        lblDetailsWar = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnSeeDetails = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 616));

        lblFilterWar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFilterWar.setForeground(new java.awt.Color(204, 204, 204));
        lblFilterWar.setText("Filtrar Guerra:");

        jtableWarList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtableWarList);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaDetailsWar.setColumns(20);
        txtAreaDetailsWar.setRows(5);
        jScrollPane2.setViewportView(txtAreaDetailsWar);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 480, 270));

        lblDetailsWar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDetailsWar.setForeground(new java.awt.Color(204, 204, 204));
        lblDetailsWar.setText("Detalles de Guerra");
        jPanel2.add(lblDetailsWar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 36));

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSave.setText("Guardar");
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 22, 168, 51));

        btnClean.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClean.setText("Limpiar");
        jPanel2.add(btnClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 85, 168, 51));

        btnSeeDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeeDetails.setText("Ver Detalles");
        jPanel2.add(btnSeeDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 148, 168, 51));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salir.png"))); // NOI18N
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusPainted(false);
        btnExit.setFocusable(false);
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 205, -1, 80));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 12, 300));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 690, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilterWar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfFilterWar, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilterWar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtfFilterWar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSeeDetails;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jtableWarList;
    private javax.swing.JLabel lblDetailsWar;
    private javax.swing.JLabel lblFilterWar;
    private javax.swing.JTextArea txtAreaDetailsWar;
    private javax.swing.JTextField txtfFilterWar;
    // End of variables declaration//GEN-END:variables
 private void setWindow() {
        setTitle("CONSULTAS");
        setLocationRelativeTo(this);
    }

}
